version: '3.8'
services:
  db:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: 5005
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: root
      MYSQL_PASSWORD: 5005
    volumes:
      - db-data:/var/lib/mysql
    ports:
      - "3307:3306"

  app:
    build: .
    environment:
      DATABASE_URL: mysql://root:5005@db:3306/mydatabase
    ports:
      - "3000:3000"
    depends_on:
      - db

volumes:
  db-data:
